name: 点灯设备监控
on:
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # ✅ 修改变量需要 contents: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python blinker_monitor.py
