name: 点灯设备监控

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: 运行脚本
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: python blinker_monitor.py
